version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.2.2-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: cuicui1/rasaactions:0.1.2
    expose:
      - "5055"
    volumes:
      - ./actions:/app/actions
