language: "zh"
pipeline:
- name: "MitieNLP" # 预训练词向量
  model: "data/total_word_feature_extractor_zh.dat"
- name: "JiebaTokenizer" # 分词器
- name: "CRFEntityExtractor" # 实体提取器
- name: "EntitySynonymMapper" # 同义词映射
- name: "RegexFeaturizer" # 正则
- name: "MitieFeaturizer" # 特征化
- name: "SklearnIntentClassifier" # 意图分类器

policies:
  - name: MemoizationPolicy
    max_history: 3
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
    restrict_rules: true
    check_for_contradictions: true
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: "FallbackPolicy"
    nlu_threshold: 0.28
    core_threshold: 0.3
    fallback_action_name: "action_default_fallback"
    ambiguity_threshold: 0.1