responses:
  utter_answer_affirm:
    - text: "嗯嗯，好的！"
    - text: "嗯嗯，很开心能够帮您解决问题~"
    - text: "嗯嗯，还需要什么我能够帮助您的呢？"

  utter_answer_greet:
    - text: "您好！请问我可以帮到您吗？"
    - text: "您好！很高兴为您服务。请说出您要查询的功能？"

  utter_answer_goodbye:
    - text: "再见"
    - text: "拜拜"
    - text: "虽然我有万般舍不得，但是天下没有不散的宴席~祝您安好！"
    - text: "期待下次再见！"
    - text: "嗯嗯，下次需要时随时记得我哟~"
    - text: "see you!"

  utter_answer_deny:
    - text: "主人，您不开心吗？不要离开我哦"
    - text: "怎么了，主人？"

  utter_answer_thanks:
    - text: "嗯呢。不用客气~"
    - text: "这是我应该做的，主人~"
    - text: "嗯嗯，合作愉快！"

  utter_answer_whoareyou:
    - text: "您好！我是小七呀，您的AI智能助理"

  utter_answer_whattodo:
    - text: "您好！很高兴为您服务，我目前只支持查询找工作相关的哦。"

  utter_default:
    - text: "没听懂，请换种说法吧~"

  utter_ask_continue:
    - text: "请问您还要继续吗?"

  utter_noworries:
    - text: "不用客气 :)"
    - text: "没事啦"
    - text: "不客气哈，都是老朋友了 :)"

  utter_wrong_business:
    - text: "当前还不支持{business}业务，请重新输入。"

  utter_wrong_type:
    - text: "当前还不支持查询{type}。"

  utter_wrong_number:
    - text: "您输入的{number}有误，请重新输入。"

  utter_answer_jobask:
    - text: "你想找什么样的工作"

